### ISSUE TITLE
state.txt timestamp format

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-replication-ng#1]
I just gave your script a try and found a few minor issues that might impact interoperability:

* Current format: `timestamp=2020-02-23T18\:12\:02Z`
* New format: `timestamp=2020-02-23T19:11:27+01:00`

Issues:
* Old format used some escaping for ":" and had a single character timezone indicator
* timestamp should be in UTC format (regardless of my local system settings)

**Comment by zerebubuth** [comment]
Yup, I'd rather not spend time replicating bug-for-bug compatibility in new / experimental code, especially if we're not totally sure it's necessary.

Thanks for taking a look at the code. Unfortunately, I should have put a big warning on it saying that it was just an experiment. It is very likely unlikely to be used - at least, not in its current state. Sorry! I hope you didn't spend too much time reviewing it!

**Comment by mmd-osm** [comment]
Don't worry, I just gave it a quick try and didn't look at the code in any way yet.

I know that some applications are parsing those fields and carry them around all the time (Overpass API comes to mind). What you see in an Overpass response header "`<meta osm_base="2020-02-23T18:35:02Z"/>` is a direct result of what was included in the state.txt file. Changing the timezone would have some negative effect here, same as not using an UTC timestamp. I'm not sure about the backslash. Hyrum's law tells us that someone will actually depend on it.

**Comment by mmd-osm** [comment]
Fast forward a few years later... osmdbt settled for this custom plugin approach. However, since PostgreSQL 10, pgoutput is part of the official PostgreSQL product with no custom plugins or additional installation steps needed anymore. Custom plugins also don't play well with some cloud offerings.

I've created an osmdbt fork now which doesn't need any custom plugins anymore, and leverages the official pgoutput plugin instead: https://github.com/mmd-osm/osmdbt-pgoutput
